[mypy]
ignore_missing_imports = true
explicit_package_bases = true

[mypy-aioesphomeapi.api_pb2]
follow_imports = skip

[mypy-noise.*]
follow_imports = skip

[mypy-google.protobuf.*]
follow_imports = skip
